-- Script was generated by Devart dbForge Schema Compare for MySQL, Version 3.0.114.0
-- Product Home Page: http://www.devart.com/dbforge/mysql/schemacompare
-- Script date 10/18/2013 10:10:33 AM
-- Server version: 5.5.23
-- Run this script against testdb to synchronize it with evandb
-- Please backup your target database before running this script

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

SET NAMES 'utf8';
USE testdb;


--
-- Alter table "jobs_edw"
--
ALTER TABLE jobs_edw
  CHANGE COLUMN admin_notes admin_notes VARCHAR(4000) DEFAULT NULL,
  ADD COLUMN updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER admin_notes,
  ADD COLUMN updated_by INT(11) DEFAULT NULL AFTER updated_at,
  ADD COLUMN CPara_rewrite TEXT DEFAULT NULL AFTER updated_by,
  ADD COLUMN LPara_rewrite TEXT DEFAULT NULL AFTER CPara_rewrite,
  ADD COLUMN Attached_at DATE DEFAULT NULL AFTER LPara_rewrite;

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
